version: 1.0.0.{build}.{branch}
os: Visual Studio 2015
  
before_build:
 - cmd: dotnet restore ./src/ivanskononenko.com.dataaccess
 - cmd: dotnet restore ./src/ivanskononenko.com

build_script:
 - cmd: dotnet build ./src/ivanskononenko.com.dataaccess
 - cmd: dotnet build ./src/ivanskononenko.com
